#!/bin/bash
# 

cd "$(dirname "${BASH_SOURCE[0]}")"
current_dir=$(pwd -P)
cd ../
pwd

if [[ -f michi2_v04_test ]]; then rm michi2_v04_test; fi

clang++ -std=c++11 -pthread main.cpp -o michi2_v04_test

cd "$current_dir"
pwd

if [[ -f ../michi2_v04_test ]]; then 
    ../michi2_v04_test -obs flux_obsframe.dat -redshift 6.3 \
                       -lib FSPS.Padova.BaSeL.Z0.0190.EBV.lib.SED DL07.LoExCom.SPAH.lib.SED RadioPowerlaw.Single.lib.SED \
                       -out fit.out \
                       -con lib3 NORM eq SED "vLv(8,1000)*1.061619121e-06" -p 1 -filter filters.list 
                       
                       # -con lib1 index eq lib2 index \
                       
                       # 
                       # IR-radio correlation: q_IR = lg( S_(IR,8-1000) / 3750 / S_(1.4GHz) )
                       # assuming q_IR = 2.4, S_(1.4GHz) = S_(IR,8-1000) * (1.0 / (10**2.4 * 3750))
                       # 
                       
else
    echo "Error! ../michi2_v04_test does not exist!"
fi

if [[ -f fit.out && -f fit.out.info ]]; then
    ./run_plotting_bestfit.sh
fi
