#!/bin/bash
# 

if [[ -f test_filter_curve ]]; then rm test_filter_curve; fi

clang++ -I../3rd/epsplot -I../ -Wno-format-security -std=c++11 test_filter_curve.cpp -o test_filter_curve

if [[ -f test_filter_curve ]]; then
    ./test_filter_curve
    ls
fi


